version: "3.9"
services:
  redev:
    build:
      context: ./env
      dockerfile: Dockerfile
    image: re-lab:latest
    container_name: re-lab-dev
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    ulimits:
      core: 0
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,lambda,cloudwatch,iam,sts,apigateway,dynamodb
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
